name: spat_loc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - numpy=2.4
  - scipy=1.17
  - matplotlib=3.10
  - h5py=3.16
  - pyvista=0.48
  - vtk=9.6
  - cython=3.2
  - pip
  - pip:
      - cyclopts==4.16.1
      - rich-rst==2.0.1
